name: "Terraforming prod"

on:
  push:
    branches:
      - 'main'
jobs:
  deploy-dev:
    name: "Terraforming prod"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Auth to gcp
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.TSM_TERRAFORM_PROD }}
      - name: terraform init
        run: terraform init
        working-directory: terraform/env/prod
      - name: Plan terraform
        run: terraform plan
        working-directory: terraform/env/prod
        env:
          TF_VAR_slackbot_auth_token: ${{ secrets.SLACKBOT_AUTH_TOKEN }}
      - name: Apply terraform
        run: terraform apply -auto-approve
        working-directory: terraform/env/prod
        env:
          TF_VAR_slackbot_auth_token: ${{ secrets.SLACKBOT_AUTH_TOKEN }}
